mrnugget/monkeylang

- content/_index.md
👻 
Feel free to update the description as you see fit~
> Add Ghost to list of Monkeys

- content/_index.md
Also, removed an extra `.` I happened to notice a few lines up.
> Add David's Typescript implementation

- content/_index.md
Add the https://github.com/MarioAriasC/monkey.kt implementation
> Add a Kotlin implementation

- content/_index.md
Add a new crystal implementation and correct the text of my Kotlin implementation.
> Add Crystal implementation

- content/_index.md
Add [MonkeyLang.jl](https://github.com/lucifer1004/MonkeyLang.jl)
> Add MonkeyLang.jl

- content/_index.md
I added four new implementations:
* Scala
* Ruby
* Python
* Lua
> A few more implementations

- content/_index.md
Hi. 
It is an implementation of Monkey in Swift.
Thanks.
> Add SwiftyMonkey

- content/_index.md
Pi is an object-oriented, dynamically-typed programming language built from the foundations of the Monkey interpreter.
> the pi programming language

- content/_index.md
- layouts/shortcodes/monkey-implementation.html
Let me know if you have any suggestions about handling of "gitlab.com", I sort of just hacked it in.
> Implementation: findley/monkey-lang

- content/_index.md
The PR contains an implementation of an interpreter for the Monkey Programming Language.
> Added monkey interpreter written in Rust

- content/_index.md
Add an implementation of an interpreter for Monkey in Java
> Add new implementation in Java

- content/_index.md
A Monkey interpreter written in Elm with an online [playgound](https://elm-monkey-interpreter.netlify.app/).
> Add dwayne/elm-monkey-interpreter

- content/_index.md
Monkey interpreter, compiler and formatter, in Rust, with added features.
> Add Yag000/chimpanzee

- content/_index.md
Updated implementations to include my implementation of the monkey lang interpreter.
[wzid/monkey-rs](https://github.com/wzid/monkey-rs)
> Add implementation

- content/_index.md
Added my code to the implementation list.
> Add bpetermann/node-interpreter to _index.md

- content/_index.md
Another Go implementation.
I added syntax sugar for UFCS and trailing lambdas
Also developed two VS Code extensions while I was at it.
> Add moritz-tiesler/monkey to _index.md

- content/_index.md
I seriously thought that I had a (somewhat) unique idea before discovering the monkeys in the wild haha
Thanks, it was a lot of fun!
PS: This is my first ever Rust code, please don't judge me.
> yet another wasm based playground

- content/_index.md
Added my implementation. 
Was a lot of fun, thanks!
> add typescript interpreter and compiler 

- content/_index.md
I figured, why not add it to the list of awesome monkey implementations?
> Add Javier-varez/monkey_interpreter implementation

- content/_index.md
Had lots of fun especially in debugging bugs :)
> Add Lilac Interpreter
